apiVersion: v1
kind: Namespace
metadata:
  name: forum
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: forum-env
  namespace: forum
data:
  FLASK_APP: app.py
  FLASK_DEBUG: "True"
  SQLALCHEMY_DATABASE_URI: sqlite:////app/database/forum.db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: forum
  namespace: forum
spec:
  replicas: 1
  selector:
    matchLabels:
      app: forum
  template:
    metadata:
      labels:
        app: forum
    spec:
      initContainers:                   # delete initContainers section (up to containers: line) if you have a persistant config
      - name: db-init
        image: ivanzalac/forum
        command: ["flask", "db", "upgrade"]
        envFrom:
        - configMapRef:
            name: forum-env
        volumeMounts:
        - name: forum-db
          mountPath: /app/database
      containers:
      - name: forum
        image: ivanzalac/forum
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: forum-env
        volumeMounts:
        - name: forum-db
          mountPath: /app/database
        startupProbe:
          httpGet:
            path: /
            port: 5000
          failureThreshold: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: forum-db
        emptyDir: {}                   # Change for production to a non-ephemeral solution
---
apiVersion: v1
kind: Service
metadata:
  name: forum
  namespace: forum
spec:
  selector:
    app: forum
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: NodePort
